#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : pypi-dkimpy
Version  : 1.1.7
Release  : 7
URL      : https://files.pythonhosted.org/packages/b6/f6/044ac1c96ff31e74cff7c0417f9cb76f86f98a6fb0a95f2f024103f0f39e/dkimpy-1.1.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/b6/f6/044ac1c96ff31e74cff7c0417f9cb76f86f98a6fb0a95f2f024103f0f39e/dkimpy-1.1.7.tar.gz
Summary  : DKIM (DomainKeys Identified Mail), ARC (Authenticated Receive Chain), and TLSRPT (TLS Report) email signing and verification
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-dkimpy-bin = %{version}-%{release}
Requires: pypi-dkimpy-license = %{version}-%{release}
Requires: pypi-dkimpy-man = %{version}-%{release}
Requires: pypi-dkimpy-python = %{version}-%{release}
Requires: pypi-dkimpy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(dnspython)
BuildRequires : pypi(py3dns)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
dkimpy - DKIM (DomainKeys Identified Mail)
https://launchpad.net/dkimpy/
Friendly fork of:
http://hewgill.com/pydkim/

%package bin
Summary: bin components for the pypi-dkimpy package.
Group: Binaries
Requires: pypi-dkimpy-license = %{version}-%{release}

%description bin
bin components for the pypi-dkimpy package.


%package license
Summary: license components for the pypi-dkimpy package.
Group: Default

%description license
license components for the pypi-dkimpy package.


%package man
Summary: man components for the pypi-dkimpy package.
Group: Default

%description man
man components for the pypi-dkimpy package.


%package python
Summary: python components for the pypi-dkimpy package.
Group: Default
Requires: pypi-dkimpy-python3 = %{version}-%{release}

%description python
python components for the pypi-dkimpy package.


%package python3
Summary: python3 components for the pypi-dkimpy package.
Group: Default
Requires: python3-core
Provides: pypi(dkimpy)
Requires: pypi(dnspython)
Requires: pypi(py3dns)

%description python3
python3 components for the pypi-dkimpy package.


%prep
%setup -q -n dkimpy-1.1.7
cd %{_builddir}/dkimpy-1.1.7
pushd ..
cp -a dkimpy-1.1.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719248578
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 setup.py build

popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-dkimpy
cp %{_builddir}/dkimpy-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-dkimpy/4b3d4997909dcd27683cd5f93a0530268b1dfb53 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/arcsign
/usr/bin/arcverify
/usr/bin/dkimsign
/usr/bin/dkimverify
/usr/bin/dknewkey

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-dkimpy/4b3d4997909dcd27683cd5f93a0530268b1dfb53

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/arcsign.1
/usr/share/man/man1/arcverify.1
/usr/share/man/man1/dkimsign.1
/usr/share/man/man1/dkimverify.1
/usr/share/man/man1/dknewkey.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
