#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
# Source0 file verified with key 0x78D7DEFB9AD59AF1 (scott@kitterman.com)
#
Name     : pypi-dkimpy
Version  : 1.1.4
Release  : 1
URL      : https://files.pythonhosted.org/packages/01/d0/76dffbc4c1b6949085c964c22b10d098eece82cec29dc078c506989175d1/dkimpy-1.1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/01/d0/76dffbc4c1b6949085c964c22b10d098eece82cec29dc078c506989175d1/dkimpy-1.1.4.tar.gz
Source1  : https://files.pythonhosted.org/packages/01/d0/76dffbc4c1b6949085c964c22b10d098eece82cec29dc078c506989175d1/dkimpy-1.1.4.tar.gz.asc
Summary  : DKIM (DomainKeys Identified Mail), ARC (Authenticated Receive Chain), and TLSRPT (TLS Report) email signing and verification
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-dkimpy-bin = %{version}-%{release}
Requires: pypi-dkimpy-license = %{version}-%{release}
Requires: pypi-dkimpy-man = %{version}-%{release}
Requires: pypi-dkimpy-python = %{version}-%{release}
Requires: pypi-dkimpy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(dnspython)
BuildRequires : pypi(py3dns)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
dkimpy - DKIM (DomainKeys Identified Mail)
https://launchpad.net/dkimpy/
Friendly fork of:
http://hewgill.com/pydkim/

%package bin
Summary: bin components for the pypi-dkimpy package.
Group: Binaries
Requires: pypi-dkimpy-license = %{version}-%{release}

%description bin
bin components for the pypi-dkimpy package.


%package license
Summary: license components for the pypi-dkimpy package.
Group: Default

%description license
license components for the pypi-dkimpy package.


%package man
Summary: man components for the pypi-dkimpy package.
Group: Default

%description man
man components for the pypi-dkimpy package.


%package python
Summary: python components for the pypi-dkimpy package.
Group: Default
Requires: pypi-dkimpy-python3 = %{version}-%{release}

%description python
python components for the pypi-dkimpy package.


%package python3
Summary: python3 components for the pypi-dkimpy package.
Group: Default
Requires: python3-core
Provides: pypi(dkimpy)
Requires: pypi(dnspython)
Requires: pypi(py3dns)

%description python3
python3 components for the pypi-dkimpy package.


%prep
%setup -q -n dkimpy-1.1.4
cd %{_builddir}/dkimpy-1.1.4
pushd ..
cp -a dkimpy-1.1.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1684517628
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-dkimpy
cp %{_builddir}/dkimpy-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-dkimpy/4b3d4997909dcd27683cd5f93a0530268b1dfb53 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/arcsign
/usr/bin/arcverify
/usr/bin/dkimsign
/usr/bin/dkimverify
/usr/bin/dknewkey

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-dkimpy/4b3d4997909dcd27683cd5f93a0530268b1dfb53

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/arcsign.1
/usr/share/man/man1/arcverify.1
/usr/share/man/man1/dkimsign.1
/usr/share/man/man1/dkimverify.1
/usr/share/man/man1/dknewkey.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
